Vagrant.configure("2") do |linuxLab|
  linuxLab.vm.define "Debian13" do |db|
    db.vm.box = "cloud-image/debian-13"
    db.ssh do |ssh|
      ssh.port = 2201
      ssh.keys_only = false
    end
    db.vm.hostname = "debian-bw"
#    db.disksize.size = "5GB"
    db.vm.provider "virtualbox" do |v|
      v.name = "debian-bw"
      v.check_guest_additions = true
      v.memory = 512
      v.cpus = 1
      v.gui = false
    end
  end

  linuxLab.vm.define "Rockylinux9" do |db|
    db.vm.box = "rockylinux/9"
    db.ssh do |ssh|
      ssh.port = 2202
      ssh.keys_only = false
    end
    db.vm.hostname = "rhel9"
#    db.disksize.size = "5GB"
    db.vm.provider "virtualbox" do |v|
      v.name = "rhel8"
      v.check_guest_additions = true
      v.memory = 512
      v.cpus = 1
      v.gui = false
    end
  end
end
